#!/usr/bin/env python3
"""
Generates commands/mit_rooms.h: every room /quickroom and /quicknear track availability for.

Data sources:
  - Hydrant (https://hydrant.mit.edu/latest.json): every room a class meets in this term.
  - classrooms.mit.edu registrar classroom list (/classrooms/eventRegRooms/search), the rooms
    QuickRoom draws from. Touchstone-protected, so this needs a logged-in session cookie.

Rerun each term (Hydrant's room list changes with the class schedule).

Usage: CLASSROOMS_COOKIE='JSESSIONID=...; _shibsession_...=...' python3 scripts/gen_room_list.py > commands/mit_rooms.h
       (copy the Cookie header from any request to classrooms.mit.edu in your browser's devtools)
"""
import json, os, re, sys, urllib.request

HYDRANT = "https://hydrant.mit.edu/latest.json"
REGISTRAR_ROOMS = "https://classrooms.mit.edu/classrooms/eventRegRooms/search"

# Hydrant also has locations like "VIRTUAL" or "KRESGE"; only keep real room numbers like "W41-1119" or "14N-112".
ROOM_PATTERN = re.compile(r"^[A-Z]*\d+[A-Z]*-[A-Z]?\d+[A-Z]?$")

def log(*a): print(*a, file=sys.stderr)

def fetch_json(url, cookie=None):
    req = urllib.request.Request(url, headers={"Accept": "application/json", **({"Cookie": cookie} if cookie else {})})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read().decode())

def hydrant_rooms():
    data = fetch_json(HYDRANT)
    rooms = set()
    for cls in data["classes"].values():
        for kind in ("lecture", "recitation", "lab", "design"):
            for _times, room in cls.get(kind + "Sections", []):
                rooms.add(room.upper())
    return data["termInfo"]["urlName"], rooms

def registrar_rooms(cookie):
    try:
        data = fetch_json(REGISTRAR_ROOMS, cookie)
    except json.JSONDecodeError:
        sys.exit("classrooms.mit.edu didn't return JSON; CLASSROOMS_COOKIE is probably expired.")
    return {r["room"].upper() for r in data["data"]["eventRegRooms"]}

def natural_key(room):
    return [(0, int(c), "") if c.isdigit() else (1, 0, c) for c in re.findall(r"\d+|\D+", room)]

def main():
    cookie = os.environ.get("CLASSROOMS_COOKIE")
    if not cookie: sys.exit("Set CLASSROOMS_COOKIE (see usage in this script's docstring).")

    log("Fetching Hydrant...")
    term, from_hydrant = hydrant_rooms()
    log("Fetching registrar classroom list...")
    from_registrar = registrar_rooms(cookie)

    rooms = sorted((r for r in from_hydrant | from_registrar if ROOM_PATTERN.match(r)), key=natural_key)
    log(f"{len(rooms)} rooms ({len(from_hydrant)} from Hydrant, {len(from_registrar)} from the registrar list)")

    print("#pragma once")
    print("// GENERATED by scripts/gen_room_list.py -- do not edit by hand.")
    print("//")
    print("// Every room /quickroom and /quicknear track availability for: rooms a class meets in this")
    print(f"// term (Hydrant, term {term}) plus the registrar classroom list QuickRoom draws from.")
    print("// Rooms that turn out to be unusable go in room_blocklist.h, not here.")
    print()
    print("#include <string>")
    print("#include <vector>")
    print()
    print("namespace mit_rooms {")
    print()
    print("inline const std::vector<std::string> rooms = {")
    for i in range(0, len(rooms), 8):
        print("    " + " ".join(f'"{r}",' for r in rooms[i:i + 8]))
    print("};")
    print()
    print("} // namespace mit_rooms")

if __name__ == "__main__":
    main()
